# Generated by Django 5.2 on 2025-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sented',
            field=models.BooleanField(default=False),
        ),
    ]
